title: Bruno Petrungaro
description: "Data Scientist and Econometrician working on Causal AI, Machine Learning, Econometrics, and Operations Research"
theme: minima

url: "https://br1pa.github.io"
baseurl: ""

header_pages:
  - cv.md
  - research.md
  - code.md

minima:
  skin: auto
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/br1pa"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/bruno-petrungaro-8b2851137/"

show_excerpts: true

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
